merciletri/blog/urls.py
from django.urls import path, include
from . import views

app_name = 'blog'

urlpatterns = [
    # the 'name' value as called by the {% url %} template tag
    path('', views.BlogIndex.as_view(), name = 'blog_index'),
    path('article/<int:pk>', views.DetailArticle.as_view(), name = 'article'),
    path('article/<int:pk><int:city_id><str:city_name>/', views.search_on_article_page),
    path('article/<int:pk><int:city_id><str:city_name>/<int:zone_id><str:zone_name>/', views.search_on_article_page),
]

merciletri/home/urls.py
from django.urls import path, include
from . import views

app_name = 'home'

urlpatterns = [
    # the 'name' value as called by the {% url %} template tag
    path('', views.home, name = 'home'),
    path('<int:city_id><str:city_name>/', views.home, name = 'home'),
    path('<int:city_id><str:city_name>/<int:zone_id><str:zone_name>/', views.home, name = 'home'),

]

merciletri/merciletri/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('blog/', include('blog.urls')),
    path('search/', include('search.urls')),
    path('private/', include('private.urls')),
    path('game/', include('game.urls')),
]

# serve static media files in dev
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

merciletri/home/views.py
from django.shortcuts import render
from search.models import City, CollectLocation, Zone, Garbage, GarbageType

def home(request, city_id=None, zone_id=None, city_name=None, zone_name=None, garbage_name=None):
    """
        get the city
    """

    city_image = ""
    cities = City.objects.all()
    city_name = city_name
    zones = None
    zone_name = zone_name
    garbages = None
    type_id = None
    selected_garbage = None
    garbage_locations = []
    garbage_name = garbage_name
    
    if request.method == "POST":

        if city_id is None and zone_id is None:
            selected_city = request.POST.get("selected_city", None)

            for city in cities :
                if selected_city == city.name :
                    city_image = city.image.url
                    city_id = city.id
                    city_name = city.name
                    break;

            zones = Zone.objects.filter(city_id=city_id)
        
        elif zone_id is None:
            zones = Zone.objects.filter(city_id=city_id)
            
            selected_zone = request.POST.get("selected_zone", None)

            for zone in zones :
                if selected_zone == zone.name :
                    zone_id = zone.id
                    zone_name = zone.name
                    break;

            garbages = Garbage.objects.all()

        else:

            garbages = Garbage.objects.all()

            selected_garbage = request.POST.get("selected_garbage", None)

            type_id = None

            for garbage in garbages :
                selected_garbage_without_spaces =(selected_garbage).join("")
                garbage_name_without_spaces = (garbage.name).join("")
                if selected_garbage_without_spaces == garbage_name_without_spaces :
                    type_id = garbage.garbagetype_id
                    garbage_name = garbage.name
                    break;

            collectlocation = CollectLocation.objects.filter(zone=zone_id)

            for CurrentLoc in collectlocation:
                try:
                    GarbageLoc = CurrentLoc.type.get(id=type_id)
                    try:
                        day_loc = CurrentLoc.day.get()
                        time_loc = CurrentLoc.time.get()
                        garbage_locations.append(f"Pour ce déchet, la collecte se fait {CurrentLoc.name} le {day_loc} {time_loc}")
                    except:
                        #todo faire un code spécifiques pour les horaires des décheteries
                        pass
                except:
                    #todo faire un message si pas de réponse 
                    pass

    return render(
        request, 
        'home/home.html', 
        {
            "cities": cities, 
            "city_image": city_image, 
            "city_id": city_id,
            "city_name": city_name,
            "zones": zones, 
            "zone_id": zone_id,
            "zone_name": zone_name,
            "garbages": garbages, 
            "selected_garbage": selected_garbage,
            "garbage_locations": garbage_locations,
            "garbage_name" : garbage_name,
        }
    )

merciletri/home/templates/home/home.html
{% extends "home/main_layout.html" %}
{% load static %}

{%block navigator_title %}
    Merci le Tri - Accueil
{% endblock navigator_title %}




{% block insert_content %}
<div class="insert row">
    <div class="col-lg-2 col-md-12">
        <img src="{% static 'home/images/onlylogo.png' %}" alt='Logo Merci le Tri'/>
    </div>
    <div class="col-lg-10 col-md-12">
        <p>La première application web qui t'aide à trier tes déchets dans la bonne poubelle</p>
    </div>
</div>
{% endblock %}


{% block search_top %}
<!--search-->
<div class="row" id="form">
    <div class="col-12">
        <p>Pour savoir où déposer votre déchet,</p>
        <fieldset>
            {% if not city_id %}
            <form action="{% url 'home:home' %}" method="post">
                {% csrf_token %}
                <label for="city_select">Sélectionnez une ville : </label>
                <select name="selected_city">
                    {% for city in cities %}
                    <option value={{city.name}}> {{city.name}} </option>
                    {% endfor %}
                </select>
                <input type="submit" value="Je valide !">
            </form>

            {% elif not zone_id %}
            <p>Ville sélectionnée : {{city_name}}</p>
            <form action="{% url 'home:home' city_id city_name %}" method="post">
                {% csrf_token %}
                <label for="zone_select">Sélectionnez une zone d'après l'image ci_dessous : </label>
                <select name="selected_zone">
                    {% for zone in zones %}
                    <option value={{zone.name}}> {{zone.name}} </option>
                    {% endfor %}
                </select>
                <input type="submit" value="Je valide !">
            </form>
            <div class=map>
                <img src="{{ city_image }}" alt="{{ City.name }}" title="{{ City.name }}">
            </div>
            {% elif not garbage_locations %}
            <p>Ville sélectionnée : {{city_name}}</p>
            <p>Zone sélectionnée : {{zone_name}}</p>
            <form action="{% url 'home:home' city_id city_name zone_id zone_name %}" method="post">
                {% csrf_token %}
                <label for="garbage_select">Sélectionnez un déchet : </label>
                <select name="selected_garbage">
                    {% for garbage in garbages %}
                        <option value={{garbage.id}}> {{garbage.name}} </option>
                    {% endfor %}
                </select>
                <input type="submit" value="Je valide !">
            </form>

            {% else %}
            <p>Ville sélectionnée : {{city_name}}</p>
            <p>Zone sélectionnée : {{zone_name}}</p>

            <p>Déchet sélectionné : {{garbage_name }} </p>

            {% for location in garbage_locations %}
            <ul>
                <li> {{ location }} </li>
            </ul>
            {% endfor %}
            {% endif %}

        </fieldset>
    </div>
</div>
{% endblock %}

{% block cards %}
<hr>
<!--other pages-->
<div class="row">
    <div class="col-12">
        <h2>Des astuces pour mieux trier</h2>
    </div>
</div>
<!--cards-->
<div class="row" id="card">
    <!--card#1-->
    <div class="col-lg-4 col-sm-12">
        <div class="card-container">
            <div class="card-img">
                <img class="card-img-item" src="{% static 'home/images/chemin_foret.jpg' %}" alt="Forêt">
                <div class="card-img-icon">
                    <span class="card-img-icon-text">recycler</span>
                </div>
            </div>
            <div class="card-infos">
                <h3 class="card-infos-title">10 bonnes pratiques pour recycler efficacement</h3>
                <a class="card-infos-button" href="/blog/article/6">Read more <i
                        class="fas fa-arrow-right arrow"></i></a>
            </div>
        </div>
    </div>
    <!--card#2-->
    <div class="col-lg-4 col-sm-12">
        <div class="card-container">
            <div class="card-img">
                <img class="card-img-item" src="{% static 'home/images/frog.jpg' %}" alt="Grenouille">
                <div class="card-img-icon">
                    <span class="card-img-icon-text">donner</span>
                </div>
            </div>
            <div class="card-infos">
                <h3 class="card-infos-title">Où, quoi, comment donner?</h3>
                <a class="card-infos-button" href="/blog/article/7">Read more <i
                        class="fas fa-arrow-right arrow"></i></a>
            </div>
        </div>
    </div>
    <!--card#3-->
    <div class="col-lg-4 col-sm-12">
        <div class="card-container">
            <div class="card-img">
                <img class="card-img-item" src="{% static 'home/images/poubelle_verte.jpg' %}"  alt="Poubelle verte">
                <div class="card-img-icon">
                    <span class="card-img-icon-text">composter</span>
                </div>
            </div>
            <div class="card-infos">
                <h3 class="card-infos-title">Avec ou sans jardin, on peut composter!</h3>
                <a class="card-infos-button" href="/blog/article/8">Read more <i
                        class="fas fa-arrow-right arrow"></i></a>
            </div>
        </div>
    </div>
</div>
{% endblock %}

merciletri/home/templates/home/main_layout.html
<!DOCTYPE html>
<html lang="fr">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script type="text/javascript" src="/merciletri/home/static/home/js/game.js' %}"></script>

    <!--bootstrap-->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css"
        integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <!--fontawesome (icon)-->
	<script src="https://kit.fontawesome.com/4fa30db326.js" crossorigin="anonymous"></script>
    <!--google font-->
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Courgette&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Oswald:wght@200&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Roboto+Mono:wght@300&display=swap" rel="stylesheet"> 
    <!--css file-->
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'home/home.css' %}">
    <script type="text/javascript" src="{% static 'home/js/game.js' %}"></script>

    <!-- Title of the page on navigator -->
    <title>{%block navigator_title %}Merci le Tri{% endblock navigator_title %}</title>
</head>

<body>
    <div class="container">

        <header>
            <!--nav menu-->
            <div class="row" id="nav">
                <div class="col-12">
                    <nav class="nav navbar navbar-expand-lg navbar-toggleable-md">
                        <!--button-->
                        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#myTopnav"
                            aria-controls="myTopnav" aria-expanded="false" aria-label="Toggle navigation">
                            <img class="logo align-center" src="{% static 'home/images/logo.png' %}"
                            alt="Logo Merci le tri">
                            <span class="icon"><i class="fas fa-bars"></i></span>
                        </button>
                        <div class="topnav collapse navbar-collapse" id="myTopnav">
                            <div class="navbar-nav">
                                <a class="navbar-brand" href="/">
                                    <img class="logo align-center" src="{% static 'home/images/logo.png' %}"
                                        alt="Logo Merci le tri">
                                </a>
                                <a class="navbar-item nav-link" href="#">Page Personnelle</a>
                                <a class="navbar-item nav-link" href="/game/">Jouer</a>
                                <a class="navbar-item nav-link" href="/blog/">Articles</a>
                                <a class="navbar-item nav-link" href="#">Géolocalisation</a>
                                <form action="/search/" class="navbar-form navbar-item nav-link">
                                    <input type="submit" class="input-smform-control2 search" value="Rechercher">
                                </form>
                            </div>
                        </div>
                    </nav>
                </div>
            </div>
        </header>

        <main>

            <section id = "article">
                <!--title-->
                <div class="row" id="title">
                    <div class="col-12">
                        <h2 class="title"> {% block page_title %} Bienvenue sur le site Merci le Tri {% endblock page_title %}</h2>
                    </div>
                </div>
                <!--content-->
                {% block article_content %} 
                {% endblock %}
            </section>

            <section id = "animation">
                {% block animation %}
                {% endblock %}
            </section>

            <section id = "game">
                {% block game %}
                {% endblock %}
            </section>
            
            <section id = "search_top">
                {% block search_top %}
                {% endblock %}
            </section>

            <section  id = "cards">
                {% block cards %}
                {% endblock %}
            </section>
            
            <section id = "insert"> 
                {% block insert_content %}
                {% endblock %}
            </section>

            <section id = "search">
                {% block search %}
                {% endblock %}
            </section>

        </main>

        <footer>
            <div class="row" id="footer">
                <div class="col-12">
                    <div class="footer">
                        <div class="footer-logo">
                            <a href="#" class="footer-link"><img src="{% static 'home/images/logo.png' %}" alt="Logo Merci le tri" class="footer-logo-item"></a>
                        </div>
                        <a href="#" class="footer-link">Contact</a>
                        <a href="#" class="footer-link">Politique de cookies</a>
                        <a href="#" class="footer-link">Plan du site</a>
                        <a href="#" class="footer-link">Condition d'utilisation</a>
                        <a href="#" class="footer-link">Politique de confidentialité</a>
                        <div class="footer-icons">
                            <a href="#" class="footer-link footer-icon"><i class="fab fa-twitter"></i></a>
                            <a href="#" class="footer-link footer-icon"><i class="fab fa-instagram"></i></a>
                            <a href="#" class="footer-link footer-icon"><i class="fab fa-facebook-square"></i></a>
                        </div>
                    </div>
                    <div class="copyright">
                        <p> &copy; Copyright 2021</p>
                    </div>
                </div>
            </div>
        </footer>

    </div>

	<script src="https://code.jquery.com/jquery-3.5.1.min.js"
		integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>
	<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>

</body>

</html>