merciletri/blog/urls.py
from django.urls import path, include
from . import views

app_name = 'blog'

urlpatterns = [
    # the 'name' value as called by the {% url %} template tag
    path('', views.BlogIndex.as_view(), name = 'blog_index'),
    path('article/<int:pk>', views.DetailArticle.as_view(), name = 'article'),
    path('article/<int:pk><int:city_id><str:city_name>/', views.search_on_article_page),
    path('article/<int:pk><int:city_id><str:city_name>/<int:zone_id><str:zone_name>/', views.search_on_article_page),
]

merciletri/merciletri/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('blog/', include('blog.urls')),
    path('search/', include('search.urls')),
    path('private/', include('private.urls')),
    path('game/', include('game.urls')),
]

# serve static media files in dev
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

merciletri/search/urls.py
from django.urls import path, include

from . import views

app_name = 'search'

urlpatterns = [
    # the 'name' value as called by the {% url %} template tag
    path('', views.search_city, name = 'search_city'),
    path('<int:city_id><str:city_name>/', views.search_city, name = 'search_city'),
    path('<int:city_id><str:city_name>/<int:zone_id><str:zone_name>/', views.search_city, name = 'search_city'),
]

merciletri/search/models.py
from django.db import models
from django.db.models.fields import Field


class City(models.Model):
    """
        manage the City class
    """

    name = models.CharField(
        "Nom de la ville",
        max_length = 100
    )

    image = models.ImageField(
        "Image",
        upload_to = "",
        blank = True
    )

    def __str__(self):
        """
            
        """

        return f"{self.name}"

    class Meta:
        """
            
        """

        verbose_name = "Ville"
        verbose_name_plural = "Villes"
        ordering = ["name"]


class Zone(models.Model):
    """
        manage the Zone class
    """

    name = models.CharField(
        "Zone",
        max_length = 100
    )

    city = models.ForeignKey(
        City,
        # if a zone is deleted, all the dependant locations will be kept
        on_delete = models.PROTECT,   
    )

    def __str__(self):
        """
            
        """

        return f"{self.name}"

    class Meta:
        """
            
        """

        verbose_name = "Zone"
        verbose_name_plural = "Zones"
        ordering = ["name"]

class GarbageType(models.Model):
    """
        manage the Garbage Type class
    """

    name = models.CharField(
        "Type de déchet",
        max_length = 100
    )

    def __str__(self):
        """
            
        """

        return f"{self.name}"

    class Meta:
        """
            
        """

        verbose_name = "Type de déchet"
        verbose_name_plural = "Types de déchet"
        ordering = ["name"]

class Garbage(models.Model):
    """
        manage the Garbage class
    """

    name = models.CharField(
        "Nom du déchet",
        max_length = 100
    )

    image = models.ImageField(
        "Image",
        upload_to = "",
        blank = True
    )

    destination = models.CharField(
        "Destination",
        max_length = 60,
        null = False,
        default = "Poubelle d'ordures ménagères"
    )

    garbagetype = models.ForeignKey(
        GarbageType,
        # if a type is deleted, all the dependant garbages will be kept
        on_delete = models.PROTECT,   
    )

    def __str__(self):
        """
            
        """

        return f"{self.name}"

    class Meta:
        """
            
        """

        verbose_name = "Déchet"
        verbose_name_plural = "Déchets"
        ordering = ["name"]

class Time(models.Model):
    """
        manage the Time class
    """

    collecttime = models.CharField(   #! charfield car on note l'heure en texte ?
        "Heure de collecte",
        max_length = 100,
        blank = True
    )

    wintertime = models.CharField(   #! charfield car on note l'heure en texte ?
        "Heure d'hiver",
        max_length = 100,
        blank = True
    )

    summertime = models.CharField(   #! charfield car on note l'heure en texte ?
        "Heure d'été'",
        max_length = 100,
        blank = True
    )

    def __str__(self):
        """
            
        """

        if self.collecttime:
            time = self.collecttime
        elif self.wintertime:
            time = self.wintertime + " (du 2 nomembre au 14 mars)"
        else:
            time = self.summertime + " (du 15 mars au 31 octobre)"
        
        return f"{time}"

    class Meta:
        """
            
        """

        verbose_name = "Horaire"
        verbose_name_plural = "Horaires"
        ordering = ["collecttime"]

class Day(models.Model):
    """
        manage the Day class
    """

    nameday = models.CharField(
        "Jour",
        max_length = 50
    )

    def __str__(self):
        """
            
        """

        return f"{self.nameday}"

    class Meta:
        """
            
        """

        verbose_name = "Jour"
        verbose_name_plural = "Jours"
        ordering = ["nameday"]

class CollectLocation(models.Model):
    """
        manage the Collect Location class
    """

    name = models.CharField(
        "Lieu de collecte",
        max_length = 150
    )

    zone = models.ForeignKey(
        Zone,
        # if a zone is deleted, all the dependant collect location will be kept
        on_delete = models.PROTECT,   
    )

    day = models.ManyToManyField(
        Day
    )

    time = models.ManyToManyField(
        Time
    )

    type = models.ManyToManyField(
        GarbageType
    )

    def __str__(self):
        """
            
        """

        return f"{self.name}"

    class Meta:
        """
        """

        verbose_name = "Lieu de collecte"
        verbose_name_plural = "Lieux de collecte"
        ordering = ["name"]

merciletri/search/views.py
from django.shortcuts import render
from .models import City, CollectLocation, Zone, Garbage, GarbageType

def search_city(request, city_id=None, zone_id=None, city_name=None, zone_name=None, garbage_name=None):
    """
        get the city
    """

    city_image = ""
    cities = City.objects.all()
    city_name = city_name
    zones = None
    zone_name = zone_name
    garbages = None
    type_id = None
    selected_garbage = None
    garbage_locations = []
    garbage_name = garbage_name

    if request.method == "POST":

        if city_id is None and zone_id is None:
            selected_city = request.POST.get("selected_city", None)

            for city in cities :
                if selected_city == city.name :
                    city_image = city.image.url
                    city_id = city.id
                    city_name = city.name
                    break;

            zones = Zone.objects.filter(city_id=city_id)
        
        elif zone_id is None:
            zones = Zone.objects.filter(city_id=city_id)
            selected_zone = request.POST.get("selected_zone", None)

            for zone in zones :
                if selected_zone == zone.name :
                    zone_id = zone.id
                    zone_name = zone.name
                    break;

            garbages = Garbage.objects.all()

        else:
            garbages = Garbage.objects.all()
            
            selected_garbage = request.POST.get("selected_garbage", None)

            type_id = None

            for garbage in garbages :
                if selected_garbage == garbage.id:
                    type_id = garbage.garbagetype_id
                    garbage_name = garbage.name
                    break;

                # selected_garbage_without_spaces =(selected_garbage).join("")
                # garbage_name_without_spaces = (garbage.name).join("")
                # if selected_garbage_without_spaces == garbage_name_without_spaces :
                #     type_id = garbage.garbagetype_id
                #     garbage_name = garbage.name
                #     break;

            collectlocation = CollectLocation.objects.filter(zone=zone_id)

            for CurrentLoc in collectlocation:
                try:
                    garbage_loc = CurrentLoc.type.get(id=type_id)
                    try:
                        day_loc = CurrentLoc.day.get()
                        time_loc = CurrentLoc.time.get()
                        garbage_locations.append(f"Pour ce déchet, la collecte se fait {CurrentLoc.name} le {day_loc} {time_loc}")
                    except:
                        #todo faire un code spécifiques pour les horaires des décheteries
                        pass
                except:
                    #todo faire un message si pas de réponse 
                    pass

    return render(
        request, 
        'search/search.html', 
        {
            "cities": cities, 
            "city_image": city_image, 
            "city_id": city_id,
            "city_name": city_name,
            "zones": zones, 
            "zone_id": zone_id,
            "zone_name": zone_name,
            "garbages": garbages, 
            "selected_garbage": selected_garbage,
            "garbage_locations": garbage_locations,
            "garbage_name" : garbage_name,
        }
    )

merciletri/search/templates/search/search.html
{% extends "home/main_layout.html" %}

{%block navigator_title %}
    Merci le Tri - Recherche
{% endblock navigator_title %}

{% block page_title %}
    Où va ce déchet ?
{% endblock page_title %}

{% block article_content %}
    <div class="row" id="form">
        <div class="col-12">

            {% if not city_id %}
                <form action="{% url 'search:search_city' %}" method="post">
                    {% csrf_token %}
                    <label for="city_select">Sélectionnez une ville : </label>
                    <select name="selected_city">
                        {% for city in cities %}
                            <option value={{city.name}}> {{city.name}} </option>
                        {% endfor %}
                    </select>
                    <input type="submit" value="Je valide !">
                </form>

            {% elif not zone_id %}
                <p>Ville sélectionnée : {{city_name}}</p>
                <form action="{% url 'search:search_city' city_id city_name %}" method="post">
                    {% csrf_token %}
                    <label for="zone_select">Sélectionnez une zone d'après l'image ci_dessous : </label>
                    <select name="selected_zone">
                        {% for zone in zones %}
                            <option value={{zone.name}}> {{zone.name}} </option>
                        {% endfor %}
                    </select>
                    <input type="submit" value="Je valide !">
                </form>
                <div class=map>
                    <img src="{{ city_image }}" alt="{{ City.name }}" title="{{ City.name }}">
                </div>

            {% elif not garbage_locations %}
                <p>Ville sélectionnée : {{city_name}}</p>
                <p>Zone sélectionnée : {{zone_name}}</p>
                <form action="{% url 'search:search_city' city_id city_name zone_id zone_name %}" method="post">
                    {% csrf_token %}
                    <label for="garbage_select">Sélectionnez un déchet : </label>
                    <select name="selected_garbage">
                        {% for garbage in garbages %}
                            <option value={{garbage.name}}> {{garbage.name}} </option>
                        {% endfor %}
                    </select>
                    <input type="submit" value="Je valide !">
                </form>

            {% else %}
                <p>Ville sélectionnée : {{city_name}}</p>
                <p>Zone sélectionnée : {{zone_name}}</p>
                <p>Déchet sélectionné : {{garbage_name }} </p>

                {% for location in garbage_locations %}
                    <ul>
                        <li> {{ location }} </li>
                    </ul>
                {% endfor %}
            {% endif %}
        </div>
    </div>
{% endblock %}