merciletri/blog/urls.py
from django.urls import path, include
from . import views

app_name = 'blog'

urlpatterns = [
    # the 'name' value as called by the {% url %} template tag
    path('', views.BlogIndex.as_view(), name = 'blog_index'),
    path('article/<int:pk>', views.DetailArticle.as_view(), name = 'article'),
    path('article/<int:pk><int:city_id><str:city_name>/', views.search_on_article_page),
    path('article/<int:pk><int:city_id><str:city_name>/<int:zone_id><str:zone_name>/', views.search_on_article_page),
]

merciletri/game/urls.py
# imports
from django.urls import path, include

# models imports
from . import views

# namespace
app_name = 'game'

# routes
urlpatterns = [
    path("", views.game, name="game"),
    path("<int:garbage_id>/", views.game, name="game"),
]

merciletri/merciletri/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('blog/', include('blog.urls')),
    path('search/', include('search.urls')),
    path('private/', include('private.urls')),
    path('game/', include('game.urls')),
]

# serve static media files in dev
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

merciletri/game/models.py
from django.db import models

merciletri/game/views.py
from django.shortcuts import render
from search.models import City, CollectLocation, Zone, Garbage, GarbageType

import random


def game(request, garbage_id=None):
    """

    """

    running = False
    dest_resultat=False
    garbages=None
    destinations = []
    selected_garbage=None
    image=None
    resultat=""
    selected_destination= None
    good_destination=None
    sel_dest="OUPS"

    if request.method == "POST":
        ask_running = request.POST.get("ask_running", None)
        selected_destination = request.POST.get("selected_destination", None)

        # get all the garbages
        garbages = Garbage.objects.all().order_by('destination').distinct('destination')

        # get all destinations without duplicates 
        destinations = []
        for dest in garbages:
            destinations.append(dest.destination)

        if ask_running :
            running = True

            # get image of one garbage randomly
            selected_garbage = random.choice(Garbage.objects.all())
            image = selected_garbage.image
            garbage_id = selected_garbage.id

        if selected_destination:
            dest_resultat = True
            garbage = Garbage.objects.get(id=garbage_id)
            if garbage.destination == destinations[int(selected_destination)]:
                resultat = "C'est gagné !"
            else:
                good_destination = garbage.destination
                resultat = "Perdu..."

            # for garb in garbage:

            #     #test
            #     sel_dest = (selected_destination).replace("a","X")
                
            #     if sel_dest == garb.destination:
            #         good_destination = garb.destination
            #         resultat = "C'est gagné !"
            #     else:
            #         good_destination = garb.destination
            #         resultat = "Perdu"

    return render(
        request, 
        'game/game.html',
        {
            "Garbages" : garbages,
            "Destinations" : destinations,
            "Selected_garbage" : selected_garbage,
            "Image" : image,
            # "Garbage_id": garbage_id,
            "Dest_resultat" : dest_resultat,
            "Resultat" : resultat,
            "Running": running,
            "selected_destination":selected_destination,
            "Good_destination": good_destination,
            # "sel_dect":sel_dest,
            # "garbage": garbage,
            # "test_dest_garb": test_dest_garb
        })

merciletri/game/templates/game/game.html
{% extends "home/main_layout.html" %}
{% load static %}
{{ block.super }}
<script type="text/javascript" src="/merciletri/home/static/home/js/game.js' %}"></script>

{% block page_title %}  {% endblock page_title %}

{% block game %}

    {% if not Running and not Dest_resultat %}
        <section class="modules">
            <div class="row">
                <img src="{% static 'game/images/banana.png' %}" alt="Banane" id="moved-1" />
                <img src="{% static 'game/images/milk.png' %}" alt="Sales logo" id="moved-2" />
                <img src="{% static 'game/images/plastic-bottles.png' %}" alt="Purchase logo" id="moved-3" />
                <img src="{% static 'game/images/tree-leaves.png' %}" alt="Accountancy logo" id="moved-4" />
                <img src="{% static 'game/images/newspaper.png' %}" alt="Ecommerce logo" id="moved-5" />
                <img src="{% static 'game/images/can.png' %}" alt="MRP logo" id="moved-6" />
                <img src="{% static 'game/images/pizza.png' %}" alt="Project logo" id="moved-7" />
            </div>
        </section>

        <form class='response' action="{% url 'game:game' %}" method="post">
            {% csrf_token %}
            <input class="btn btn-primary" type="submit" name="ask_running" value="JOUER" />
        </form>

    {% elif not Dest_resultat %}
        <div class="game">
            <div class=img-garbage>
                <img src="{{ Image.url }}" alt="{{ Selected_garbage.name }}" title="{{ Selected_garbage.name }}">
            </div>

            <form class='response' action="{% url 'game:game' Selected_garbage.id %}" method="post">
                {% csrf_token %}
                <label for="destination_select">Où va ce déchet ? </label>
                <select name="selected_destination">
                    {% for destination in Destinations %}
                        <option value={{forloop.counter0}}> {{destination}} </option>
                    {% endfor %}
                </select>
                <input type="submit" value="Je valide !">
            </form>
        </div>

    {% else %}
        <p> {{Resultat}} </p>
        {% if Good_destination %}
            <p> La bonne réponse était : "{{Good_destination}}".</p>
        {% endif %}
        <form class='response' action="{% url 'game:game' %}" method="post">
            {% csrf_token %}
            <input class="btn btn-primary" type="submit" name="ask_running" value="rejouer" />
        </form>

    {% endif %}
{% endblock %}